#!/usr/bin/env python3
"""Generate the panel-friendly Compose definition from the standalone stack."""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true", help="Fail when the committed file is stale")
args = parser.parse_args()

# Keep the original anchors, dependencies, commands and volumes. Only replace
# env_file with explicit references and remove the standalone proxy.
source = (root / "docker-compose.yml").read_text()
before, marker, after = source.partition("  proxy:\n")
assert marker, "Cannot find standalone proxy"
_, marker, after = after.partition("  postgres:\n")
assert marker, "Cannot find PostgreSQL service"
source = before + marker + after
source = source.replace("  # Reverse proxy + Let's Encrypt. Skip the profile on platforms with their own proxy.\n", "")
source = source.replace("  env_file: .env\n", "", 1)
source = source.replace("  caddy_data:\n", "").replace("  caddy_config:\n", "")

variables = []
for line in (root / ".env.example").read_text().splitlines():
    if not line or line.startswith("#") or "=" not in line:
        continue
    key, default = line.split("=", 1)
    if key in {"COMPOSE_PROJECT_NAME", "GROVS_VERSION", "ACTIVE_STORAGE_SERVICE"}:
        continue
    # All values come from setup.sh, including matching backend/dashboard OAuth secrets.
    variables.append(f'    {key}: "${{{key}:?Run scripts/setup.sh and import the generated environment}}"'
                     if default == "change-me" else f'    {key}: "${{{key}:-}}"')
for key in ("AWS_S3_KEY_ID", "AWS_S3_ACCESS_KEY", "AWS_S3_REGION", "AWS_S3_BUCKET",
            "S3_ENDPOINT", "S3_FORCE_PATH_STYLE", "CUSTOM_DOMAINS_ENABLED",
            "CUSTOM_DOMAINS_PROVIDER", "SELF_HOSTED_INGRESS_HOST", "MIGRATIONS_ENABLED"):
    variables.append(f'    {key}: "${{{key}:-}}"')
source = source.replace("  environment:\n", "  environment:\n" + "\n".join(variables) + "\n    GROVS_EE: \"false\"\n", 1)
source = source.replace("${GROVS_VERSION:-latest}", "${GROVS_VERSION:?Select a published Grovs release}")
source = source.replace("  # One-shot on every start:", "  # One-shot during initial deployment:")
web_rule = " || ".join(f"Host(`${{{key}}}`)" for key in (
    "API_HOST", "SDK_HOST", "MCP_HOST", "GO_HOST", "LINKS_PROD_HOST", "LINKS_TEST_HOST", "PREVIEW_HOST"))
web_rule += " || HostRegexp(`^[a-z0-9-]+[.]${GROVS_LINKS_DOMAIN_PATTERN:?Run scripts/prepare-platform.sh}$$`)"
web_rule += " || HostRegexp(`^[a-z0-9-]+[.]${GROVS_TEST_DOMAIN_PATTERN:?Run scripts/prepare-platform.sh}$$`)"

def routing(service, rule, priority):
    router = "${GROVS_ROUTER_PREFIX:-grovs}-" + service
    labels = [
        "traefik.enable=true",
        "traefik.docker.network=${GROVS_PROXY_NETWORK:?Set the platform proxy network}",
        f"traefik.http.services.{router}.loadbalancer.server.port=3000",
        f"traefik.http.routers.{router}.rule={rule}",
        f"traefik.http.routers.{router}.priority={priority}",
        f"traefik.http.routers.{router}.service={router}",
        f"traefik.http.routers.{router}.entrypoints=${{GROVS_HTTPS_ENTRYPOINT:?Set the HTTPS entrypoint}}",
        f"traefik.http.routers.{router}.tls=true",
        f"traefik.http.routers.{router}.tls.certresolver=${{GROVS_CERT_RESOLVER:?Set a DNS challenge resolver}}",
        f"traefik.http.routers.{router}-http.rule={rule}",
        f"traefik.http.routers.{router}-http.priority={priority}",
        f"traefik.http.routers.{router}-http.entrypoints=${{GROVS_HTTP_ENTRYPOINT:?Set the HTTP entrypoint}}",
        f"traefik.http.routers.{router}-http.service={router}",
        f"traefik.http.routers.{router}-http.middlewares={router}-https",
        f"traefik.http.middlewares.{router}-https.redirectscheme.scheme=https",
    ]
    if service == "web":
        for i, key in enumerate(("SERVER_HOST", "DOMAIN_LIVE", "DOMAIN_TEST")):
            labels += [f"traefik.http.routers.{router}.tls.domains[{i}].main=${{{key}}}",
                       f"traefik.http.routers.{router}.tls.domains[{i}].sans=*.${{{key}}}"]
    return "    networks: [default, proxy]\n    labels:\n" + "".join(f'      - "{label}"\n' for label in labels)

source = source.replace("  web:\n", "  web:\n" + routing("web", web_rule, 10), 1)
source = source.replace("  dashboard:\n", "  dashboard:\n" + routing("dashboard", "Host(`${DASHBOARD_HOST}`)", 100), 1)
source += "\nnetworks:\n  default:\n  proxy:\n    external: true\n    name: ${GROVS_PROXY_NETWORK:?Set the platform proxy network}\n"
source = "# Generated by scripts/generate-platform-compose.py; do not edit by hand.\n" + source.split("\n", 1)[1]
target = root / "docker-compose.platform.yml"
if args.check:
    if not target.exists() or target.read_text() != source:
        raise SystemExit("docker-compose.platform.yml is stale; run scripts/generate-platform-compose.py")
else:
    target.write_text(source)
