#!/usr/bin/env bash
set -euo pipefail
# Application variables are required fields in the Vultr vendor console.
metadata() {
  curl --fail --silent --show-error --max-time 10 --retry 6 \
    --header 'Metadata-Token: vultr' "http://169.254.169.254/v1/internal/app-$1"
}
DOMAIN=$(metadata grovs_domain)
ADMIN_EMAIL=$(metadata grovs_admin_email)
# Values are arguments, never evaluated as shell code. Secrets are generated by setup.
/usr/local/bin/grovs-setup "$DOMAIN" "$ADMIN_EMAIL"
